#!/bin/bash

VE_DIR=ve

echo "checking install path"
if [[ ! -d bootstrap ]]; then
    echo "must be called in project dir, as 'bootstrap/manjaro'!"
    exit 2
fi

echo "checking environment"
virtualenv --version > /dev/null 2>&1 || sudo pacman -S python-virtualenv
jhead -V > /dev/null 2>&1 || sudo pacman -S jhead
metapixel --version > /dev/null 2>&1 || sudo pacman -S metapixel
# pandoc -v > /dev/null 2>&1 || sudo pacman -S pandoc
exiftool -ver > /dev/null 2>&1 || sudo pacman -S perl-image-exiftool
pngquant --help > /dev/null 2>&1 || sudo yaourt --noconfirm -S pngquant

echo "preparing virtualenv in '$VE_DIR'"
rm -rf $VE_DIR
virtualenv -p /usr/bin/python2 $VE_DIR
. $VE_DIR/bin/activate

pip install pybuilder
pyb install_dependencies

ln -sf $PWD/src/main/scripts/* $PWD/$VE_DIR/bin
ln -sf $PWD/src/main/python/* $PWD/$VE_DIR/lib/python*/site-packages

echo "remember to 'source $VE_DIR/bin/activate' as first step."
