#!/bin/bash
set -e -E -u

VE_DIR=ve-$(uname -msr | sed "s/ /-/g")

echo "checking install path"
if [[ ! -d bootstrap ]]; then
    echo "must be called in project dir, as 'bootstrap/$(basename $0)'!"
    exit 2
fi

echo "checking environment"
virtualenv --version > /dev/null 2>&1 || brew install pyenv-virtualenv
jhead -V > /dev/null 2>&1 || brew install jhead
# metapixel --version > /dev/null 2>&1 || sudo pacman -S metapixel
exiftool -ver > /dev/null 2>&1 || brew install exiftool
pngquant --help > /dev/null 2>&1 || brew install pngquant
mogrify --help > /dev/null 2>&1 || brew install imagemagick

echo "preparing virtualenv in '$VE_DIR'"
rm -rf $VE_DIR
virtualenv -p /usr/local/bin/python2 $VE_DIR
set +u
. $VE_DIR/bin/activate
set -u

pip install pybuilder
pyb install_dependencies

(
	cd $VE_DIR/bin
	ln -sf ../../src/main/scripts/* .
)
(
	cd $VE_DIR/lib/python*/site-packages
	ln -sf ../../../../src/main/python/* .
)

echo "remember to 'source $VE_DIR/bin/activate' as first step."
