#!/usr/bin/env python
"""
Usage: analyze-photos --photos-dir=DIRS... --faces-dir=DIR --tiles-dir=DIR [--picasa-contacts-file=XMLFILE]
"""
import sys
from docopt import docopt
from photolib.analyze import Analyzer

arguments = docopt(__doc__)
print arguments

ps = Analyzer(photos_dirs=arguments["--photos-dir"],
        faces_dir=arguments["--faces-dir"],
        tiles_dir=arguments["--tiles-dir"],
        picasa_contacts_file=arguments["--picasa-contacts-file"])
sys.exit(ps.main())
