#!/bin/bash
set -e -E -u

NAME=${1:?no NAME given?!}
shift

OUT_DIR=out
CACHE_DIR=$OUT_DIR/cache
GALLERIES_DIR=$OUT_DIR/galleries
GALLERY_DIR=$GALLERIES_DIR/$NAME
REVEAL_DIR=$CACHE_DIR/reveal.js
TITLE_IMAGE=00montage.jpg

echo "generating a html gallery"

if [[ ! -d $REVEAL_DIR ]]; then
    echo "-- caching reveal.js"
    mkdir -p $CACHE_DIR
    (
        cd $CACHE_DIR
        git clone https://github.com/hakimel/reveal.js.git
    )
fi

rm -rf "$GALLERY_DIR"
mkdir -p "$GALLERY_DIR"

echo "-- preparing gallery in $GALLERY_DIR"
mkdir -p "$GALLERY_DIR/reveal.js"
cp -r $REVEAL_DIR/js $REVEAL_DIR/css $REVEAL_DIR/lib "$GALLERY_DIR/reveal.js"
cp -r gallery/* "$GALLERY_DIR"

echo "-- converting photos"
GALLERY_MD="$GALLERY_DIR/$NAME.md"
rm -f "$GALLERY_MD"
touch "$GALLERY_MD"
exec 3> "$GALLERY_MD"

for PHOTO in "$@"; do
    PHOTO_NAME=$(basename "$PHOTO")
    echo "---- converting $PHOTO_NAME"
    convert "$PHOTO" -resize 800x600\> -unsharp 0x1 -quality 85 "$GALLERY_DIR/$PHOTO_NAME"
done

echo "-- creating first slide"
montage -geometry +4+4 -resize 100x100^ -crop 100x100+0+0 +repage -background none "$GALLERY_DIR/*.jpg" "$GALLERY_DIR/$TITLE_IMAGE"

echo "-- adding slides"
for PHOTO in "$GALLERY_DIR"/*.jpg; do
    PHOTO_NAME=$(basename "$PHOTO")
    echo "---- adding $PHOTO_NAME"
    TITLE=""
    if [[ "$PHOTO_NAME" = "$TITLE_IMAGE" ]]; then
        TITLE="$NAME"
    fi
    echo "# $TITLE {data-background=\"$PHOTO_NAME\" data-background-size=\"contain\" .whitetext}" >&3
    echo >&3
done
exec 3>&-

echo "-- rendering html"
pandoc --slide-level 1 -V transition=linear -V backgroundTransition=slide \
    -i -s --mathjax -i -t revealjs --template my --data-dir "$GALLERY_DIR" \
    --css photolib.css "$GALLERY_MD" -o "$GALLERY_DIR/index.html"

echo "done."
