#!/bin/bash
set -e -E -u

NAME=${1:?no NAME given?!}
shift

OUT_DIR=out
CACHE_DIR=$OUT_DIR/cache
GALLERIES_DIR=$OUT_DIR/galleries
GALLERY_DIR=$GALLERIES_DIR/$NAME
REVEAL_DIR=$CACHE_DIR/reveal.js

echo "generating a html gallery"

if [[ ! -d $REVEAL_DIR ]]; then
    echo "-- caching reveal.js"
    mkdir -p $CACHE_DIR
    (
        cd $CACHE_DIR
        git clone https://github.com/hakimel/reveal.js.git
    )
fi

rm -rf $GALLERY_DIR
mkdir -p $GALLERY_DIR

echo "-- preparing gallery in $GALLERY_DIR"
mkdir -p $GALLERY_DIR/reveal.js
cp -r $REVEAL_DIR/js $REVEAL_DIR/css $REVEAL_DIR/lib $GALLERY_DIR/reveal.js
cp -r gallery/* $GALLERY_DIR

echo "-- generating gallery source"
GALLERY_MD=$GALLERY_DIR/$NAME.md
rm -f $GALLERY_MD
exec 3> $GALLERY_MD
for PHOTO in "$@"; do
    echo "---- adding $PHOTO"
    cp "$PHOTO" $GALLERY_DIR
    PHOTO_NAME=$(basename "$PHOTO")
    echo "# {data-background=\"$PHOTO_NAME\" data-background-size=\"cover\"}" >&3
    echo >&3
    #echo "# {data-background=\"$PHOTO_NAME\" data-background-size=\"contain\"}" >&3
    #echo >&3
done
exec 3>&-

echo "-- rendering html"
pandoc --slide-level 1 -V transition=linear -V backgroundTransition=fade \
    -i -s --mathjax -i -t revealjs --template my --data-dir $GALLERY_DIR \
    --css photolib.css $GALLERY_MD -o $GALLERY_DIR/$NAME.html

echo "done."
