#!/usr/bin/env python
"""Usage:
    prepare-mosaic --tiles-dir=DIR
"""
import sys
from docopt import docopt
from photolib.mosaic import Preparer

arguments = docopt(__doc__)

preparer = Preparer(tiles_dir=arguments["--tiles-dir"])
sys.exit(preparer.main())
