#!/usr/bin/env python
"""
Usage:
    prepare-tiles --tiles-dir=DIR
"""
from docopt import docopt
from photolib.mosaic import Preparer

arguments = docopt(__doc__)

preparer = Preparer(tiles_dir=arguments["--tiles-dir"])
preparer.main()
