#!/usr/bin/env python
"""
Usage: search-photos --photos-dir=DIR... [--picasa-contacts-file=XMLFILE] [--database=FILE] [--outputdir=DIR] SEARCHTERM...
"""
import logging
import os
import shutil
import sys
from docopt import docopt

from photolib.picasadb import PicasaDb

arguments = docopt(__doc__)
print arguments

pdb = PicasaDb(photos_dirs=arguments["--photos-dir"],
        picasa_contacts_file=arguments["--picasa-contacts-file"])

database_file = arguments["--database"]
if not database_file:
    database_file = "photolib.cache"

if os.path.exists(database_file):
    pdb.import_db(database_file)
if not pdb.database:
    pdb.build_db()
    pdb.store_db(database_file)

result = None
for term in arguments["SEARCHTERM"]:
    print "searching for %s" % term
    if result is None:
        result = set(pdb.database[term])
    else:
        result = result & set(pdb.database[term])

outputdir = arguments["--outputdir"]
if outputdir:
    if os.path.exists(outputdir):
        shutil.rmtree(outputdir)
    os.makedirs(outputdir)
    for f in result:
        shutil.copy2(f, outputdir)
    logging.info("photos copied to %s" % outputdir)

print "\n".join(result)

#sys.exit(pdb.main())
