#!/bin/sh

exiftool -all= \
    -P \
    -overwrite_original \
    -tagsfromfile @ \
    -ICC_Profile \
    -ThumbnailImage \
    -EXIF:ColorSpace= \
    -EXIF:LightSource \
    -EXIF:FileSource \
    -EXIF:SceneType \
    -EXIF:Make \
    -EXIF:Model \
    -EXIF:Artist="Lars Tiede" \
    -EXIF:Copyright="Lars Tiede" \
    -EXIF:ModifyDate \
    -EXIF:ExposureTime \
    -EXIF:FNumber \
    -EXIF:ISO \
    -EXIF:DateTimeOriginal \
    -EXIF:CreateDate \
    -EXIF:ShutterSpeedValue \
    -EXIF:ApertureValue \
    -EXIF:MaxApertureValue \
    -EXIF:Flash \
    -EXIF:FocalLength \
    -EXIF:FocalLengthIn35mmFormat \
    -EXIF:LensInfo \
    -EXIF:LensModel \
    $*


