#!/usr/bin/env python
"""
Usage:
    transfer-photos --source-dir=DIR... --photos-dir=DIR
"""

import sys

from docopt import docopt

from photolib.transfer import PhotoImporter


arguments = docopt(__doc__)
pi = PhotoImporter(
        source_dirs=arguments["--source-dir"],
        photos_dir=arguments["--photos-dir"]
)
sys.exit(pi.main())
