#!/usr/bin/env python
"""
Usage:
    transfer-photos --source-dir=DIR... --photos-dir=DIR [--artist=TEXT] [--exifdata=TEXT...]
"""

import sys

from docopt import docopt

from photolib.transfer import PhotoImporter


arguments = docopt(__doc__)
pi = PhotoImporter(
        source_dirs=arguments["--source-dir"],
        photos_dir=arguments["--photos-dir"],
        artist=arguments["--artist"],
        exifdata=arguments["--exifdata"]
)
sys.exit(pi.main())
